- name: nginx install and run
  hosts: nginx
  # hosts: all
  serial: 3
  become: yes #take sudo access
  vars_files:
  - /var/expense/credentials_mysql.yaml #ansible server
  # serial: 3
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: nginx
      state: present
  
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes